# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20170605_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=30)),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Project')),
            ],
        ),
        migrations.AddIndex(
            model_name='costrecord',
            index=models.Index(fields=['project', 'payer'], name='sheets_cost_project_8cabe8_idx'),
        ),
        migrations.AddIndex(
            model_name='costrecord',
            index=models.Index(fields=['project', 'payer', 'calculated'], name='sheets_cost_project_c57fc5_idx'),
        ),
    ]
