# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrecord',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
