# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_auto_20170605_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrecord',
            name='category',
            field=models.CharField(choices=[('FO', 'Food'), ('CL', 'Clothing'), ('HO', 'Housing'), ('TR', 'Transportation'), ('ED', 'Education'), ('EN', 'Entertainment'), ('OT', 'Others')], db_index=True, default='OT', max_length=2),
        ),
    ]
