# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_auto_20170605_2312'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='costrecord',
            index=models.Index(fields=['project', 'payer'], name='sheets_cost_project_8cabe8_idx'),
        ),
        migrations.AddIndex(
            model_name='costrecord',
            index=models.Index(fields=['project', 'payer', 'calculated'], name='sheets_cost_project_c57fc5_idx'),
        ),
    ]
