# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170604_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.date.today, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.date.today, null=True, verbose_name='Start date'),
        ),
    ]
